pipeline {
	agent none
	stages {
		stage('Setup Docker Agent') {
			// Run application in container with dependencies installed
			agent {
				docker {
                                        image 'nmm131/terraform-aws-ansible-jenkins-k8-elastic-devops-pipeline'
					// '-e HOME=/tmp' fixes withCredentials' "mkdir /.docker permission denied" error
					args '-e HOME=/tmp -v /root/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock'
				}
			}
			stages {
				stage('Compile-Package-Test') {
					steps {
						script {
							// Run application
							sh 'python3 flask/app.py &'
							sh 'sleep 1'
							// Check response of application after running
							// Stop Jenkins Build if application is not responding
							sh '''
								if [ curl -sL --fail http://0.0.0.0:5000 -o /dev/null ]
								then
									echo "Application successfully running!"
								else
									echo "Application isn\'t responding!"
									#currentBuild.result = 'ABORTED'
									#error('Application isn't responding! Stopping early…')
								fi
								'''
						}
					}
				}
			}
		}
		stage('Deploy') {
			steps {
				node('master') {
					script {
						// Deploy application using kubernetes
                                                sh 'kubectl apply -f /var/jenkins_home/workspace/terraform-aws-ansible-jenkins-k8-elastic-devops-pipeline/kubernetes/kubernetes-app.yaml'
					}
				}
			}
		}
	}
}
