---
- hosts: localhost 
  tasks:
    - name: Install Docker
      shell: |
        sudo yum update -y
        sudo amazon-linux-extras install docker -y
        sudo service docker start
        sudo usermod -a -G docker ec2-user
    - name: Install Jenkins
      # Environment variables pose security risk
      shell: |
        sudo docker build -t jenkins:jcasc /tmp/ansible-aws/jcasc
        sudo docker run -u root -d --name jenkins -p 8080:8080 -v /var/jenkins_home:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock --env JENKINS_ADMIN_ID=admin --env JENKINS_ADMIN_PASSWORD=password jenkins:jcasc
        #- hosts: ec2-cluster
        #    - name: Install kubernetes
        #      # install Kubernetes
        #      # if .kube directory does not exist, create it and copy kubernetes admin configuration to it
        #      # then set ownership of kubernetes admin config file needed to run kubernetes
        #      shell: |
        #        sudo apt update && sudo apt install -y apt-transport-https gnupg2 curl
        #        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        #        sudo install minikube-linux-arm64 /usr/local/bin/minikube
        #        mkdir -p $HOME/.kube
        #        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        #        sudo chown $(id -u):$(id -g) $HOME/.kube/config
        #        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        #        curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        #        echo "$(<kubectl.sha256) kubectl" | sha256sum --check
        #        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        #        mkdir -p ~/.local/bin/kubectl
        #        mv ./kubectl ~/.local/bin/kubectl
        #        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        #        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        #        sudo apt-get update
        #        sudo apt-get install -y kubectl
